### ISSUE TITLE
Trouble passing arguments in?

### ISSUE THREAD

**Issue by Permafacture** [LLukas22/vLLM-haystack-adapter#4]
I am using vLLM to load an AWQ quantized model due to vRAM constraints. I found that setting the max_model_len to 2**13 was necessary to get this to work.

This code successfully runs for me:

```
from vllm import LLM, SamplingParams
prompts = [whatever]
sampling_params = SamplingParams(temperature=0.9, top_p=0.95, max_tokens=2**12)
llm = LLM(model="TheBloke/dolphin-2.2.1-mistral-7B-AWQ", quantization="AWQ", max_model_len=2**13)
outputs = llm.generate(prompts, sampling_params)
```

Trying to translate this vllm-haystack I get an OOM error when I instantiate the `prompt_model`. 
 
```
from haystack.nodes import PromptNode, PromptModel
from vllm_haystack import vLLMLocalInvocationLayer

model_id = "TheBloke/dolphin-2.2.1-mistral-7B-AWQ"
prompt_model = PromptModel(model_name_or_path=model_id,
                           invocation_layer_class=vLLMLocalInvocationLayer,
                           model_kwargs={
                               "max_model_len": 2**13,
                               "quantization": "AWQ"
                               })
prompt_node = PromptNode(model_name_or_path=prompt_model, top_k=1, max_length=512)
```

I expect it's that the crucial max_model_len is not being passed in or some other argument in the creation of the underlying LLM object is not being set correctly. How can I best recreate the working vLLM example in the context of haystack?

**Comment by LLukas22** [comment]
Currently the `vLLMLocalInvocationLayer` is set up to pass any kwargs set on `vLLM_kwargs` directly into the vLLM `LLM` class. (see [here](https://github.com/LLukas22/vLLM-haystack-adapter/blob/main/src/vllm_haystack/__init__.py#L314C9-L314C184)).

I think what happens here is that you need to "warp" the vLLM kwargs again in the `model_kwargs` as they get unwrapped once when the `vLLMLocalInvocationLayer` is constructed. 
E.g.
```python
prompt_model = PromptModel(model_name_or_path=model_id,
                           invocation_layer_class=vLLMLocalInvocationLayer,
                           model_kwargs={
                               "vLLM_kwargs": {
                                 "max_model_len": 2**13,
                                 "quantization": "AWQ"
                                 }
                               })

```

This isn't very user friendly, but i always thought of the `vLLM_kwargs` as something that is rarely/never used. Maybe we should allow users to consturct the vLLM `LLM` object externally and then pass it into the `vLLMLocalInvocationLayer`. 🤔

**Comment by Permafacture** [comment]
This worked. Thanks! I think it would make more sense to pass the LLM object in directly. Also, it would be nice if the vLLMLocalInvocationLayer didn't silently allow unrecognized kwargs to pass through.
